[package]
name = "zellij-relay-protocol"
version.workspace = true
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition.workspace = true
description = "Protocol types shared between Zellij and the zellij-relay tunnel server"
license.workspace = true
include = ["src/**/*", "assets/"]

[dependencies]
anyhow = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
aes-gcm = { workspace = true }
hmac = { workspace = true }
spake2 = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
